name: Test Backup Script

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  schedule:
    - cron: '0 12 * * *'  # Exécution quotidienne à 12h UTC
  workflow_dispatch:  # Permet d'exécuter manuellement depuis GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV  # Ajout du chemin src au PYTHONPATH

      - name: Run tests
        run: pytest --junitxml=report.xml  # Exécute les tests et génère un rapport au format XML

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USER}}
          password: ${{secrets.EMAIL_PASS}}
          subject: "Résultat des tests GitHub Actions"
          body: "Les tests ont été exécutés. Voir les résultats ci-joints."
          to: mehdipailot@hotmail.fr  # Adresse de réception des notifications
          from: "GitHub Actions <noreply@github.com>"
          attachments: report.xml  # Joindre le rapport des tests au mail
